# Generated by Django 3.0.3 on 2020-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sldt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='des',
            name='name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='des',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
