# Generated by Django 3.0.3 on 2020-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sldt', '0003_auto_20200408_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
